/**
 * Top US universities by international student enrollment (SEVP/ICE 2024 data).
 * Used for institution name autocomplete in ContextStep and ZeroIncomeStep.
 * Each entry: [name, city, state].
 */
export const US_UNIVERSITIES: [string, string, string][] = [
  ["New York University", "New York", "NY"],
  ["Northeastern University", "Boston", "MA"],
  ["Columbia University", "New York", "NY"],
  ["University of Southern California", "Los Angeles", "CA"],
  ["Arizona State University", "Tempe", "AZ"],
  ["University of Illinois Urbana-Champaign", "Champaign", "IL"],
  ["Purdue University", "West Lafayette", "IN"],
  ["University of California, Los Angeles", "Los Angeles", "CA"],
  ["University of California, San Diego", "La Jolla", "CA"],
  ["University of California, Berkeley", "Berkeley", "CA"],
  ["Boston University", "Boston", "MA"],
  ["University of Michigan", "Ann Arbor", "MI"],
  ["Carnegie Mellon University", "Pittsburgh", "PA"],
  ["University of Texas at Dallas", "Richardson", "TX"],
  ["University of Washington", "Seattle", "WA"],
  ["University of Pennsylvania", "Philadelphia", "PA"],
  ["University of Texas at Austin", "Austin", "TX"],
  ["Georgia Institute of Technology", "Atlanta", "GA"],
  ["University of Florida", "Gainesville", "FL"],
  ["Ohio State University", "Columbus", "OH"],
  ["Harvard University", "Cambridge", "MA"],
  ["Stanford University", "Stanford", "CA"],
  ["Massachusetts Institute of Technology", "Cambridge", "MA"],
  ["University of California, Davis", "Davis", "CA"],
  ["University of California, Irvine", "Irvine", "CA"],
  ["Michigan State University", "East Lansing", "MI"],
  ["Indiana University Bloomington", "Bloomington", "IN"],
  ["Pennsylvania State University", "University Park", "PA"],
  ["Texas A&M University", "College Station", "TX"],
  ["Rutgers University", "New Brunswick", "NJ"],
  ["University of Minnesota", "Minneapolis", "MN"],
  ["University of Maryland", "College Park", "MD"],
  ["University of Chicago", "Chicago", "IL"],
  ["Cornell University", "Ithaca", "NY"],
  ["Johns Hopkins University", "Baltimore", "MD"],
  ["University of Wisconsin-Madison", "Madison", "WI"],
  ["Stony Brook University", "Stony Brook", "NY"],
  ["University of California, Santa Barbara", "Santa Barbara", "CA"],
  ["Northwestern University", "Evanston", "IL"],
  ["University of Virginia", "Charlottesville", "VA"],
  ["Duke University", "Durham", "NC"],
  ["Rice University", "Houston", "TX"],
  ["Yale University", "New Haven", "CT"],
  ["Princeton University", "Princeton", "NJ"],
  ["Caltech", "Pasadena", "CA"],
  ["University of Colorado Boulder", "Boulder", "CO"],
  ["North Carolina State University", "Raleigh", "NC"],
  ["University of North Carolina at Chapel Hill", "Chapel Hill", "NC"],
  ["Virginia Tech", "Blacksburg", "VA"],
  ["University of Arizona", "Tucson", "AZ"],
  ["George Mason University", "Fairfax", "VA"],
  ["University of Houston", "Houston", "TX"],
  ["University of Pittsburgh", "Pittsburgh", "PA"],
  ["Drexel University", "Philadelphia", "PA"],
  ["Illinois Institute of Technology", "Chicago", "IL"],
  ["University of Cincinnati", "Cincinnati", "OH"],
  ["Stevens Institute of Technology", "Hoboken", "NJ"],
  ["SUNY Buffalo", "Buffalo", "NY"],
  ["University of Iowa", "Iowa City", "IA"],
  ["University of Utah", "Salt Lake City", "UT"],
  ["George Washington University", "Washington", "DC"],
  ["Georgetown University", "Washington", "DC"],
  ["Brandeis University", "Waltham", "MA"],
  ["Emory University", "Atlanta", "GA"],
  ["Tufts University", "Medford", "MA"],
  ["Vanderbilt University", "Nashville", "TN"],
  ["Washington University in St. Louis", "St. Louis", "MO"],
  ["University of Rochester", "Rochester", "NY"],
  ["Case Western Reserve University", "Cleveland", "OH"],
  ["Syracuse University", "Syracuse", "NY"],
  ["University of Notre Dame", "Notre Dame", "IN"],
  ["University of Oregon", "Eugene", "OR"],
  ["Oregon State University", "Corvallis", "OR"],
  ["University of Georgia", "Athens", "GA"],
  ["University of Connecticut", "Storrs", "CT"],
  ["University of Massachusetts Amherst", "Amherst", "MA"],
  ["Florida International University", "Miami", "FL"],
  ["University of South Florida", "Tampa", "FL"],
  ["San Jose State University", "San Jose", "CA"],
  ["San Francisco State University", "San Francisco", "CA"],
  ["University of Central Florida", "Orlando", "FL"],
  ["Florida State University", "Tallahassee", "FL"],
  ["University of Delaware", "Newark", "DE"],
  ["Iowa State University", "Ames", "IA"],
  ["Kansas State University", "Manhattan", "KS"],
  ["University of Kansas", "Lawrence", "KS"],
  ["University of Missouri", "Columbia", "MO"],
  ["University of Nebraska-Lincoln", "Lincoln", "NE"],
  ["Louisiana State University", "Baton Rouge", "LA"],
  ["Clemson University", "Clemson", "SC"],
  ["Auburn University", "Auburn", "AL"],
  ["University of Alabama", "Tuscaloosa", "AL"],
  ["University of Tennessee", "Knoxville", "TN"],
  ["University of Kentucky", "Lexington", "KY"],
  ["University of Oklahoma", "Norman", "OK"],
  ["Oklahoma State University", "Stillwater", "OK"],
  ["University of South Carolina", "Columbia", "SC"],
  ["Colorado State University", "Fort Collins", "CO"],
  ["Baylor University", "Waco", "TX"],
  ["Southern Methodist University", "Dallas", "TX"],
];
